# path:
#   raw_path: ../../data/raw/
#   processed_path: ../../data/processed/
#   files_path: ../../research/files/


# dataloader:
#   image_path: /Users/shahmuhammadraditrahman/Desktop/segGAN/data/raw/datasets.zip
#   channels: 3
#   image_size: 256
#   batch_size: 1
#   split_size: 0.20


# netG:
#   in_channels: 3

# netD:
#   in_channels: 3


### SRC ###

path:
  raw_path: ./data/raw/
  processed_path: ./data/processed/
  files_path: ./research/files/


dataloader:
  image_path: /Users/shahmuhammadraditrahman/Desktop/segGAN/data/raw/datasets.zip
  channels: 3
  image_size: 256
  batch_size: 1
  split_size: 0.20


netG:
  in_channels: 3

netD:
  in_channels: 3

model:
  beta1: 0.5
  beta2: 0.999
  lr: 0.0002
  epochs: 200
  momentum: 0.5
  dice_smooth: 0.001
  step_size: 10
  gamma: 0.1

