# path:
#   raw_path: ../../data/raw/
#   processed_path: ../../data/processed/
#   files_path: ../../research/files/


# dataloader:
#   image_path: /Users/shahmuhammadraditrahman/Desktop/segGAN/data/raw/datasets.zip
#   channels: 3
#   image_size: 256
#   batch_size: 1
#   split_size: 0.20


# netG:
#   in_channels: 3

# netD:
#   in_channels: 3


### SRC ###

path:
  raw_path: ./data/raw/
  processed_path: ./data/processed/
  files_path: ./research/files/
  train_images_path: ./outputs/train_results/
  train_model_path: ./checkpoints/model_history/
  best_model_path: ./checkpoints/best_model/
  metrics_path: ./metrics/
  test_image_path: ./outputs/test_result/


dataloader:
  image_path: /Users/shahmuhammadraditrahman/Desktop/segGAN/data/raw/datasets.zip
  channels: 3
  image_size: 256
  batch_size: 1
  split_size: 0.50


model:
  beta1: 0.5
  beta2: 0.999
  lr: 0.0002
  epochs: 20
  momentum: 0.5
  smooth: 0.001
  step_size: 10
  gamma: 0.1
  smooth: 0.001
  clamp_value: 0.01
  l1loss_value: 0.1
  adam: True
  SGD: False
  lr_scheduler: False
  weight_init: True
  display: True
  device: mps

